// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvYYQENR2K1PVw0M6iUS5YpzJudoMOIYo',
    appId: '1:283126827672:web:a5c2ad6be662b6d55f1eed',
    messagingSenderId: '283126827672',
    projectId: 'gym-app-cde0c',
    authDomain: 'gym-app-cde0c.firebaseapp.com',
    storageBucket: 'gym-app-cde0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjPeb4njo7Q4-kwm-e6p59qIQoW19sL2o',
    appId: '1:283126827672:android:dac90d8eb828c52b5f1eed',
    messagingSenderId: '283126827672',
    projectId: 'gym-app-cde0c',
    storageBucket: 'gym-app-cde0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfbVgAgE0-iQ_ux1R4pnsRXuEcpoMd-bY',
    appId: '1:283126827672:ios:9ca3a2504265b7a55f1eed',
    messagingSenderId: '283126827672',
    projectId: 'gym-app-cde0c',
    storageBucket: 'gym-app-cde0c.appspot.com',
    iosClientId: '283126827672-bic1f03hd50og43mhavbk72hjl8pc9k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfbVgAgE0-iQ_ux1R4pnsRXuEcpoMd-bY',
    appId: '1:283126827672:ios:9ca3a2504265b7a55f1eed',
    messagingSenderId: '283126827672',
    projectId: 'gym-app-cde0c',
    storageBucket: 'gym-app-cde0c.appspot.com',
    iosClientId: '283126827672-bic1f03hd50og43mhavbk72hjl8pc9k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ex',
  );
}
