// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkIpjA0hwkVJzZE5MqwcProYgnjaH03Nk',
    appId: '1:628579240146:web:3252489bc3da0a1f67450b',
    messagingSenderId: '628579240146',
    projectId: 'firp-fb44f',
    authDomain: 'firp-fb44f.firebaseapp.com',
    storageBucket: 'firp-fb44f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNovpVlO7CwdR4smntZafTgkSgqP249aw',
    appId: '1:628579240146:android:386ff64786a9892367450b',
    messagingSenderId: '628579240146',
    projectId: 'firp-fb44f',
    storageBucket: 'firp-fb44f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA2Q1UrHNt2m8LafWHM2-W3KtoR0ZkLgA',
    appId: '1:628579240146:ios:2e154b6869225bb867450b',
    messagingSenderId: '628579240146',
    projectId: 'firp-fb44f',
    storageBucket: 'firp-fb44f.appspot.com',
    iosClientId: '628579240146-mk3cqakmac924t0rh4d4dt84gu7d9ugq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA2Q1UrHNt2m8LafWHM2-W3KtoR0ZkLgA',
    appId: '1:628579240146:ios:2e154b6869225bb867450b',
    messagingSenderId: '628579240146',
    projectId: 'firp-fb44f',
    storageBucket: 'firp-fb44f.appspot.com',
    iosClientId: '628579240146-mk3cqakmac924t0rh4d4dt84gu7d9ugq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ex',
  );
}
